// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUh1GK2it7kj5iNYS29LOWD8jhvnkGB3Q',
    appId: '1:260772653301:web:0cc8132fbc3034b3b5bdbc',
    messagingSenderId: '260772653301',
    projectId: 'first-flutter-project-d6cb7',
    authDomain: 'first-flutter-project-d6cb7.firebaseapp.com',
    storageBucket: 'first-flutter-project-d6cb7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXYALbqyu4hmCVHiTzcdP7700Uppn-_w4',
    appId: '1:260772653301:android:b417eb9cd1d4c9b5b5bdbc',
    messagingSenderId: '260772653301',
    projectId: 'first-flutter-project-d6cb7',
    storageBucket: 'first-flutter-project-d6cb7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf0aDA_eg910f2yY9uNp2tdHrbeNGjWDY',
    appId: '1:260772653301:ios:0408cd070f24afffb5bdbc',
    messagingSenderId: '260772653301',
    projectId: 'first-flutter-project-d6cb7',
    storageBucket: 'first-flutter-project-d6cb7.firebasestorage.app',
    iosBundleId: 'com.example.showroomApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf0aDA_eg910f2yY9uNp2tdHrbeNGjWDY',
    appId: '1:260772653301:ios:0408cd070f24afffb5bdbc',
    messagingSenderId: '260772653301',
    projectId: 'first-flutter-project-d6cb7',
    storageBucket: 'first-flutter-project-d6cb7.firebasestorage.app',
    iosBundleId: 'com.example.showroomApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUh1GK2it7kj5iNYS29LOWD8jhvnkGB3Q',
    appId: '1:260772653301:web:fe40f94070644a05b5bdbc',
    messagingSenderId: '260772653301',
    projectId: 'first-flutter-project-d6cb7',
    authDomain: 'first-flutter-project-d6cb7.firebaseapp.com',
    storageBucket: 'first-flutter-project-d6cb7.firebasestorage.app',
  );

}